### ISSUE TITLE
Can't force Nova to use system database

### ISSUE THREAD

**Issue by nielsiano** [tenancy/hyn-nova#2]
It's trying to access [tenant] database by default. When trying to login through web or 

```bash
$ php artisan nova:user
> Database [tenant] not configured
```

I tried various things including adding a middleware to Nova forcing the `database.default` config to `system`, but I didn't have any luck.

**Comment by luceos** [comment]
Nova uses the default guard which (most likely) uses your User model, is that User model set to use the tenant connection by any chance? Since version 1.1.4 of nova one can configure the guard nova uses, so you could create a custom guard for your system users.

**Comment by nielsiano** [comment]
Haven't tried the guard approach, but will do so when time permits. For now specifically setting the UsesSystemConnection solves it, like you suggested. Thanks.

Sidenote: Ideally, I'd like to use Nova both for the system users/admins, eg. `site.com/admin` for handling Tenants, tenant databases, websites and hostnames. And then also use Nova  for `tenant.site.com/admin` which is an interface strictly for the tenant admins, where they can add and edit content, including users and roles.

**Comment by luceos** [comment]
@nielsiano you could set up that double sidedness by creating a conditional where you register the Nova Models based on the path. I guess that would be easiest.

**Comment by nielsiano** [comment]
@luceos I'll give it a go. Thanks for your help - and +1 for tenancy in general.

**Comment by luceos** [comment]
You're welcome! Let us know when you have any additional questions.
