### ISSUE TITLE
Missing a Readme 

### ISSUE THREAD

**Issue by gvsrepins** [tenancy/hyn-nova#7]
Please add a Readme file with installation instructions.

**Comment by Plytas** [comment]
Hey @gvsrepins. This package is still in development. Right now you only need to install it via composer:
```composer require tenancy/hyn-nova dev-master```

Note that this is subject to change.

**Comment by gvsrepins** [comment]
OK I understand. Thanks for the kick answer @Plytas!

**Comment by Plytas** [comment]
I'm gonna close this issue as Readme will come along with a proper release.
